site_name: Higher Computer Science

nav:
    - Home: 'index.md'
    - Software Design and Development: 
        - Development Methodologies:
          - Explanation: '01-software-development/1.1-development-methodologies.md'
          - Agile Methodologies: '01-software-development/1.2-agile-methodologies.md'
          - Iterative Methodologies: '01-software-development/1.3-the-iterative-development-Process.md'
        - Analysis:
          - Explanation: '01-software-development/2.1-analysis.md'
          - Analysis Tasks: '01-software-development/2.1.1-analysis-tasks.md'
        - Design:
          - Explanation: '01-software-development/3.1-design.md'
          - Data Flow In and Out: '01-software-development/3.1.3-data-flow-in-out.md'
          - Structure Diagrams: '01-software-development/3.1.1-structure-diagrams.md'
          - Pseudocode: '01-software-development/3.1.2-pseudocodeV1.md'
          - Wireframes: '01-software-development/3.1.4-wireframes.md'
          - Design Tasks: '01-software-development/3.1.5-design-modules-data-flow-tasks.md'
    - Computer Systems:
        - Data Representation:
          - Storing Negative Numbers: 
            - Two's Compliment: '02-computer-systems/2.1-twos-compliment.md'
            - Tasks: '02-computer-systems/2.1.1-twos-compliment-tasks.md'
    - Program Challenges:
      - Overview: 'program-challenges/index.md'
      - 🔥:
        - Name Change: 'program-challenges/level-1/Name Change.md'
        - Area Calc: 'program-challenges/level-1/Area Calc.md'
        - Largest Number: 'program-challenges/level-1/Largest Number.md'
        - Number Changer: 'program-challenges/level-1/Number Changer.md'
        - Jim's Bonus Scheme: "program-challenges/level-1/Jim's Bonus Scheme.md"
      - 🔥🔥:
        - Bigger and Bigger: 'program-challenges/level-2/Bigger and Bigger.md'
        - Form Chooser: 'program-challenges/level-2/Form Chooser.md'
        - Taxi Fare: 'program-challenges/level-2/Taxi Fare.md'
        - Password Check: 'program-challenges/level-2/Password Check.md'
        - Secret Agent: 'program-challenges/level-2/Secret Agent.md'
        - New Email: 'program-challenges/level-2/New Email.md'
        - Bonus Payment: 'program-challenges/level-2/Bonus Payment.md'
        - BMI Checker: 'program-challenges/level-2/BMI Checker.md'
        - Magic 8 Ball: 'program-challenges/level-2/Magic 8 Ball.md'
        - km to Miles: 'program-challenges/level-2/km to Miles.md'
        - Random Number Generator: 'program-challenges/level-2/Random Number Generator.md'
      - 🔥🔥🔥:
        - Ice Cream!: 'program-challenges/level-3/Ice Cream!.md'
        - Cake Maker: 'program-challenges/level-3/Cake Maker.md'
        - Five A Day: 'program-challenges/level-3/Five A Day.md'
        - Squares and Cubes: 'program-challenges/level-3/Squares and Cubes.md'
        - Lower Case: 'program-challenges/level-3/Lower Case.md'
        - Go Kart: 'program-challenges/level-3/Go Kart.md'
        - Pick A Card: 'program-challenges/level-3/Pick A Card.md'
        - Darts: 'program-challenges/level-3/Darts.md'
        - Averages: 'program-challenges/level-3/Averages.md'
        - Times Tables: 'program-challenges/level-3/Times Tables.md'
      - 🔥🔥🔥🔥:
        - Bingo!: 'program-challenges/level-4/Bingo!.md'
        - OCR Tech: 'program-challenges/level-4/OCR Tech.md'
        - OCR FC - Goals Array: 'program-challenges/level-4/OCR FC - Goals Array.md'
        - Game Time - Day Of The Week: 'program-challenges/level-4/Game Time - Day Of The Week.md'
        - Logging In: 'program-challenges/level-4/Logging In.md'
        - Email Validator: 'program-challenges/level-4/Email Validator.md'
        - Pin Checker: 'program-challenges/level-4/Pin Checker.md'
        - 6th Form Admissions: 'program-challenges/level-4/6th Form Admissions.md'
        - Free Electricity!: 'program-challenges/level-4/Free Electricity!.md'
        - How Many Cars?: 'program-challenges/level-4/How Many Cars?.md'
      - 🔥🔥🔥🔥🔥:
        - Game Time - Total Time: 'program-challenges/level-5/Game Time - Total Time.md'
        - Inverse Image: 'program-challenges/level-5/Inverse Image.md'
        - Battleships: 'program-challenges/level-5/Battleships.md'

      
markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      
theme:
  name: material
  font:
    text: Quicksand
  palette:
    scheme: default
    primary: blue
    accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
plugins:
  - glightbox

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - Styles/extra.css

    
